[profile.default]
src = 'contracts'
script = 'scripts'
out = 'build'
tst = 'tests'
libs = ['lib']

remappings = [ 
  "@overlay-protocol/v1-core/=lib/v1-core/",
  "@openzeppelin/=lib/openzeppelin-contracts/",
  "@uniswap/v3-core/=lib/v3-core/",
  "@uniswap/v3-periphery=lib/v3-periphery",
  "v3-core/=lib/v3-core/contracts/"
]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
