name: Overlay V1 Periphery Lint Solidity

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  solidity-lint:
    runs-on: ubuntu-latest
    name: Solidity Lint
    steps:
      - name: Check out source repository
        uses: actions/checkout@v2

      - name: Setup node.js
        uses: actions/setup-node@v1
        with:
          node-version: '17.x'

      - name: Install node.js dependencies
        run: npm install

      - name: Run formater check on *.sol and *.json
        run: npm run format:check

      - name: run linter check on *.sol file
        run: npm run hint
