name: Overlay V1 Periphery Test Python

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
    # increasing available memory for node reduces issues with ganache crashing
    # https://nodejs.org/api/cli.html#cli_max_old_space_size_size_in_megabytes
  NODE_OPTIONS: --max_old_space_size=4096

jobs:
  periphery:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.9]

    steps:
      - uses: actions/checkout@v2

      - name: Create env file
        run: |
          touch .env
          echo WEB3_INFURA_PROJECT_ID=${{ secrets.WEB3_INFURA_PROJECT_ID }} >> .env
          echo ETHERSCAN_TOKEN=${{ secrets.ETHERSCAN_TOKEN }} >> .env
          cat .env
          pwd
          ls ~/

      - name: Create env file for Brownie pm
        run: |
          touch ~/.brownie/packages/overlay-market/v1-core@1.0.0-beta.1/.env
          echo WEB3_INFURA_PROJECT_ID=${{ secrets.WEB3_INFURA_PROJECT_ID }} >> ~/.brownie/packages/overlay-market/v1-core@1.0.0-beta.1/.env
          echo ETHERSCAN_TOKEN=${{ secrets.ETHERSCAN_TOKEN }} >> ~/.brownie/packages/overlay-market/v1-core@1.0.0-beta.1/.env
          cat ~/.brownie/packages/overlay-market/v1-core@1.0.0-beta.1/.env

      # TODO: create env file in location of overlay-market/v1-core for brownie pm
      # TODO: /home/runner/.brownie/packages/overlay-market/v1-core@1.0.0-beta.1/.env

      - name: Cache Compiler Installations
        uses: actions/cache@v2
        with:
          path: |
            ~/.solcx
            ~/.vvm
          key: compiler-cache

      - name: Setup Node.js
        uses: actions/setup-node@v1

      - name: Install Ganache
        run: npm install -g ganache-cli@6.12.1

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Requirements
        run: pip install -r requirements.txt

      - name: Compile Code
        run: brownie compile --size

      - name: Run Tests
        run: brownie test -vv -s --gas
